name: Node.js CI/CD with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test || echo "No tests defined"

      - name: Build Docker image
        run: docker build -t node-sample-app .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag and push Docker image
        run: |
          docker tag node-sample-app ${{ secrets.DOCKERHUB_USERNAME }}/node-sample-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/node-sample-app:latest
